name: Graffiti Grid
favicon: null
layout_spectrum: 0.9826682158745825
typography_spectrum: 0.4643245222978294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#ffffff'
    - '#525252'
    - '#ff0000'
    - '#ff8000'
  brandStrength: 0.6049958057701588
  lightness: 0.2163862087763846
  saturation: 0.16974973492324352
  rhythmicContrast: 0.6968689691275358
purpose: []
