name: Graffiti Grid
favicon: null
layout_spectrum: 0.99992
typography_spectrum: 0.77494
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcf5'
    - '#a72631'
    - '#47292d'
    - '#c4c5c0'
    - '#757575'
  brandStrength: 0.6049958057701588
  lightness: 0.2163862087763846
  saturation: 0.16974973492324352
  rhythmicContrast: 0.6968689691275358
purpose: []
